//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BezerraMenezesExpress.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class db_BezerraMenezesEntities : DbContext
    {
        public db_BezerraMenezesEntities()
            : base("name=db_BezerraMenezesEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tblAssociado> tblAssociado { get; set; }
        public virtual DbSet<tblCarrinhoEntrada> tblCarrinhoEntrada { get; set; }
        public virtual DbSet<tblCategorias> tblCategorias { get; set; }
        public virtual DbSet<tblConta> tblConta { get; set; }
        public virtual DbSet<tblEstoque> tblEstoque { get; set; }
        public virtual DbSet<tblExtrato> tblExtrato { get; set; }
        public virtual DbSet<tblFluxo> tblFluxo { get; set; }
        public virtual DbSet<tblFluxoColunas> tblFluxoColunas { get; set; }
        public virtual DbSet<tblFormaPagamento> tblFormaPagamento { get; set; }
        public virtual DbSet<tblLancamento> tblLancamento { get; set; }
        public virtual DbSet<tblLivros> tblLivros { get; set; }
        public virtual DbSet<tblParcela> tblParcela { get; set; }
        public virtual DbSet<tblPerfil> tblPerfil { get; set; }
        public virtual DbSet<tblSubconta> tblSubconta { get; set; }
        public virtual DbSet<tblTipoEstoque> tblTipoEstoque { get; set; }
        public virtual DbSet<tblUsuario> tblUsuario { get; set; }
    
        public virtual int sp_fin_rep_extrato(Nullable<int> idConta, Nullable<System.DateTime> dtInicio, Nullable<System.DateTime> dtFim, string txtFiltro)
        {
            var idContaParameter = idConta.HasValue ?
                new ObjectParameter("idConta", idConta) :
                new ObjectParameter("idConta", typeof(int));
    
            var dtInicioParameter = dtInicio.HasValue ?
                new ObjectParameter("dtInicio", dtInicio) :
                new ObjectParameter("dtInicio", typeof(System.DateTime));
    
            var dtFimParameter = dtFim.HasValue ?
                new ObjectParameter("dtFim", dtFim) :
                new ObjectParameter("dtFim", typeof(System.DateTime));
    
            var txtFiltroParameter = txtFiltro != null ?
                new ObjectParameter("txtFiltro", txtFiltro) :
                new ObjectParameter("txtFiltro", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_fin_rep_extrato", idContaParameter, dtInicioParameter, dtFimParameter, txtFiltroParameter);
        }
    
        public virtual int sp_fin_rep_fluxo(Nullable<int> idConta, Nullable<System.DateTime> dtInicio)
        {
            var idContaParameter = idConta.HasValue ?
                new ObjectParameter("idConta", idConta) :
                new ObjectParameter("idConta", typeof(int));
    
            var dtInicioParameter = dtInicio.HasValue ?
                new ObjectParameter("dtInicio", dtInicio) :
                new ObjectParameter("dtInicio", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_fin_rep_fluxo", idContaParameter, dtInicioParameter);
        }
    }
}
