//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BezerraMenezesExpress.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblEstoque
    {
        public int idEstoque { get; set; }
        public long ISBN { get; set; }
        public string NotaFiscal { get; set; }
        public string dtMovimento { get; set; }
        public int idTipo { get; set; }
        public Nullable<int> Quantidade { get; set; }
        public Nullable<decimal> Valor { get; set; }
    
        public virtual tblLivros tblLivros { get; set; }
    }
}
