//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BezerraMenezesExpress.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblFluxoColunas
    {
        public int idFluxoColuna { get; set; }
        public string col01 { get; set; }
        public string col02 { get; set; }
        public string col03 { get; set; }
        public string col04 { get; set; }
        public string col05 { get; set; }
        public string col06 { get; set; }
        public string col07 { get; set; }
        public string col08 { get; set; }
        public string col09 { get; set; }
        public string col10 { get; set; }
        public string col11 { get; set; }
        public string col12 { get; set; }
    }
}
