//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BezerraMenezesExpress.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblFluxo
    {
        public int idFluxo { get; set; }
        public string Subconta { get; set; }
        public Nullable<decimal> col01 { get; set; }
        public Nullable<decimal> col02 { get; set; }
        public Nullable<decimal> col03 { get; set; }
        public Nullable<decimal> col04 { get; set; }
        public Nullable<decimal> col05 { get; set; }
        public Nullable<decimal> col06 { get; set; }
        public Nullable<decimal> col07 { get; set; }
        public Nullable<decimal> col08 { get; set; }
        public Nullable<decimal> col09 { get; set; }
        public Nullable<decimal> col10 { get; set; }
        public Nullable<decimal> col11 { get; set; }
        public Nullable<decimal> col12 { get; set; }
        public Nullable<decimal> Total { get; set; }
    }
}
