//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BezerraMenezesExpress.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblLivros
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblLivros()
        {
            this.tblCarrinhoEntrada = new HashSet<tblCarrinhoEntrada>();
            this.tblEstoque = new HashSet<tblEstoque>();
        }
    
        public long ISBN { get; set; }
        public string Titulo { get; set; }
        public string Autor { get; set; }
        public string AutorEspiritual { get; set; }
        public string Editora { get; set; }
        public string Edicao { get; set; }
        public int Categoria { get; set; }
        public Nullable<int> AnoPublicacao { get; set; }
        public string Descricao { get; set; }
        public string Capa { get; set; }
        public Nullable<int> Status { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblCarrinhoEntrada> tblCarrinhoEntrada { get; set; }
        public virtual tblCategorias tblCategorias { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblEstoque> tblEstoque { get; set; }
    }
}
