//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BezerraMenezesExpress.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblLancamento
    {
        public int idLancamento { get; set; }
        public int idConta { get; set; }
        public int idSubconta { get; set; }
        public string Descricao { get; set; }
        public Nullable<System.DateTime> Pagamento { get; set; }
        public decimal Valor { get; set; }
        public Nullable<bool> Previsto { get; set; }
    
        public virtual tblConta tblConta { get; set; }
        public virtual tblSubconta tblSubconta { get; set; }
    }
}
