//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BezerraMenezesExpress.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblParcela
    {
        public int idParcela { get; set; }
        public int idAssociado { get; set; }
        public int idformaPagamento { get; set; }
        public int idSubconta { get; set; }
        public int Ano { get; set; }
        public int Mes { get; set; }
        public System.DateTime Pagamento { get; set; }
        public decimal Valor { get; set; }
    
        public virtual tblAssociado tblAssociado { get; set; }
        public virtual tblFormaPagamento tblFormaPagamento { get; set; }
        public virtual tblSubconta tblSubconta { get; set; }
    }
}
