//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BezerraMenezesExpress.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSubconta
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblSubconta()
        {
            this.tblLancamento = new HashSet<tblLancamento>();
            this.tblParcela = new HashSet<tblParcela>();
        }
    
        public int idSubconta { get; set; }
        public string Codigo { get; set; }
        public string Descricao { get; set; }
        public Nullable<bool> Ativo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblLancamento> tblLancamento { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblParcela> tblParcela { get; set; }
    }
}
