//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BezerraMenezesExpress.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblUsuario
    {
        public int idUsuario { get; set; }
        public int idPerfil { get; set; }
        public string CodUsuario { get; set; }
        public string Nome { get; set; }
        public string Senha { get; set; }
        public string Telefone { get; set; }
        public string Email { get; set; }
        public string Celular { get; set; }
        public Nullable<System.DateTime> Nascimento { get; set; }
        public Nullable<bool> Ativo { get; set; }
    
        public virtual tblPerfil tblPerfil { get; set; }
    }
}
